CREATE TABLE ENFORCEMENT_ACTION (
       ENFORCEMENT_ACTION_TYPE_CODE VARCHAR(255) NULL,
       ENFORCEMENT_COMMENT_TEXT VARCHAR(255) NULL,
       ENFORCEMENT_DATE VARCHAR(255) NULL,
       ENFORCEMENT_ID VARCHAR(255) NULL,
       ORIGINATOR_CODE VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL
);

CREATE TABLE GEOGRAPHIC_AREA (
       ANSI_ENTITY_CODE VARCHAR(255) NULL,
       AREA_TYPE_CODE VARCHAR(255) NULL,
       CITY_SERVED VARCHAR(255) NULL,
       COUNTY_SERVED VARCHAR(255) NULL,
       EPA_REGION VARCHAR(255) NULL,
       GEO_ID VARCHAR(255) NULL,
       PRIMACY_AGENCY_CODE VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       PWS_ACTIVITY_CODE VARCHAR(255) NULL,
       PWS_TYPE_CODE VARCHAR(255) NULL,
       STATE_SERVED VARCHAR(255) NULL,
       TRIBAL_CODE VARCHAR(255) NULL,
       ZIP_CODE_SERVED VARCHAR(255) NULL
);

CREATE TABLE LCR_SAMPLE (
       EPA_REGION VARCHAR(255) NULL,
       PRIMACY_AGENCY_CODE VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       RECONCILIATION_ID VARCHAR(255) NULL,
       SAMPLE_ID VARCHAR(255) NULL,
       SAMPLING_END_DATE VARCHAR(255) NULL,
       SAMPLING_START_DATE VARCHAR(255) NULL
);

CREATE TABLE LCR_SAMPLE_RESULT (
       CONTAMINANT_CODE VARCHAR(255) NULL,
       EPA_REGION VARCHAR(255) NULL,
       PRIMACY_AGENCY_CODE VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       RESULT_SIGN_CODE VARCHAR(255) NULL,
       SAMPLE_ID VARCHAR(255) NULL,
       SAMPLE_MEASURE VARCHAR(255) NULL,
       SAR_ID VARCHAR(255) NULL,
       UNIT_OF_MEASURE VARCHAR(255) NULL
);

CREATE TABLE SERVICE_AREA (
       EPA_REGION VARCHAR(255) NULL,
       IS_PRIMARY_SERVICE_AREA_CODE VARCHAR(255) NULL,
       PRIMACY_AGENCY_CODE VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       PWS_ACTIVITY_CODE VARCHAR(255) NULL,
       PWS_TYPE_CODE VARCHAR(255) NULL,
       SERVICE_AREA_TYPE_CODE VARCHAR(255) NULL
);

CREATE TABLE TREATMENT (
       COMMENTS_TEXT VARCHAR(255) NULL,
       FACILITY_ID VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       TREATMENT_ID VARCHAR(255) NULL,
       TREATMENT_OBJECTIVE_CODE VARCHAR(255) NULL,
       TREATMENT_PROCESS_CODE VARCHAR(255) NULL
);

CREATE TABLE VIOLATION (
       COMPLIANCE_STATUS_CODE VARCHAR(255) NULL,
       COMPL_PER_BEGIN_DATE VARCHAR(255) NULL,
       COMPL_PER_END_DATE VARCHAR(255) NULL,
       CONTAMINANT_CODE VARCHAR(255) NULL,
       CORRECTIVE_ACTION_ID VARCHAR(255) NULL,
       EPA_REGION VARCHAR(255) NULL,
       FACILITY_ID VARCHAR(255) NULL,
       IS_HEALTH_BASED_IND VARCHAR(255) NULL,
       IS_MAJOR_VIOL_IND VARCHAR(255) NULL,
       LATEST_ENFORCEMENT_ID VARCHAR(255) NULL,
       ORIGINATOR_CODE VARCHAR(255) NULL,
       POPULATION_SERVED_COUNT VARCHAR(255) NULL,
       POP_CAT_5_CODE VARCHAR(255) NULL,
       PRIMACY_AGENCY_CODE VARCHAR(255) NULL,
       PRIMARY_SOURCE_CODE VARCHAR(255) NULL,
       PUBLIC_NOTIFICATION_TIER VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       PWS_ACTIVITY_CODE VARCHAR(255) NULL,
       PWS_DEACTIVATION_DATE VARCHAR(255) NULL,
       PWS_TYPE_CODE VARCHAR(255) NULL,
       RTC_DATE VARCHAR(255) NULL,
       RTC_ENFORCEMENT_ID VARCHAR(255) NULL,
       RULE_CODE VARCHAR(255) NULL,
       RULE_FAMILY_CODE VARCHAR(255) NULL,
       RULE_GROUP_CODE VARCHAR(255) NULL,
       SAMPLE_RESULT_ID VARCHAR(255) NULL,
       SEVERITY_IND_CNT VARCHAR(255) NULL,
       STATE_MCL VARCHAR(255) NULL,
       UNIT_OF_MEASURE VARCHAR(255) NULL,
       VIOLATION_CATEGORY_CODE VARCHAR(255) NULL,
       VIOLATION_CODE VARCHAR(255) NULL,
       VIOLATION_ID VARCHAR(255) NULL,
       VIOL_MEASURE VARCHAR(255) NULL
);

CREATE TABLE VIOLATION_ENF_ASSOC (
       ENFORCEMENT_ID VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       VIOLATION_ID VARCHAR(255) NULL
);

CREATE TABLE WATER_SYSTEM (
       ADDRESS_LINE1 VARCHAR(255) NULL,
       ADDRESS_LINE2 VARCHAR(255) NULL,
       ADMIN_NAME VARCHAR(255) NULL,
       ALT_PHONE_NUMBER VARCHAR(255) NULL,
       CDS_ID VARCHAR(255) NULL,
       CITY_NAME VARCHAR(255) NULL,
       COUNTRY_CODE VARCHAR(255) NULL,
       DBPR_SCHEDULE_CAT_CODE VARCHAR(255) NULL,
       EMAIL_ADDR VARCHAR(255) NULL,
       EPA_REGION VARCHAR(255) NULL,
       FAX_NUMBER VARCHAR(255) NULL,
       GW_SW_CODE VARCHAR(255) NULL,
       IS_GRANT_ELIGIBLE_IND VARCHAR(255) NULL,
       IS_SCHOOL_OR_DAYCARE_IND VARCHAR(255) NULL,
       IS_WHOLESALER_IND VARCHAR(255) NULL,
       LT2_SCHEDULE_CAT_CODE VARCHAR(255) NULL,
       ORG_NAME VARCHAR(255) NULL,
       OUTSTANDING_PERFORMER VARCHAR(255) NULL,
       OUTSTANDING_PERFORM_BEGIN_DATE VARCHAR(255) NULL,
       OWNER_TYPE_CODE VARCHAR(255) NULL,
       PHONE_EXT_NUMBER VARCHAR(255) NULL,
       PHONE_NUMBER VARCHAR(255) NULL,
       POPULATION_SERVED_COUNT VARCHAR(255) NULL,
       POP_CAT_11_CODE VARCHAR(255) NULL,
       POP_CAT_2_CODE VARCHAR(255) NULL,
       POP_CAT_3_CODE VARCHAR(255) NULL,
       POP_CAT_4_CODE VARCHAR(255) NULL,
       POP_CAT_5_CODE VARCHAR(255) NULL,
       PRIMACY_AGENCY_CODE VARCHAR(255) NULL,
       PRIMACY_TYPE VARCHAR(255) NULL,
       PRIMARY_SOURCE_CODE VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       PWS_ACTIVITY_CODE VARCHAR(255) NULL,
       PWS_DEACTIVATION_DATE VARCHAR(255) NULL,
       PWS_NAME VARCHAR(255) NULL,
       PWS_TYPE_CODE VARCHAR(255) NULL,
       SEASON_BEGIN_DATE VARCHAR(255) NULL,
       SEASON_END_DATE VARCHAR(255) NULL,
       SERVICE_CONNECTIONS_COUNT VARCHAR(255) NULL,
       SOURCE_PROTECTION_BEGIN_DATE VARCHAR(255) NULL,
       SOURCE_WATER_PROTECTION_CODE VARCHAR(255) NULL,
       STATE_CODE VARCHAR(255) NULL,
       SUBMISSION_STATUS_CODE VARCHAR(255) NULL,
       ZIP_CODE VARCHAR(255) NULL
);

CREATE TABLE WATER_SYSTEM_FACILITY (
       AVAILABILITY_CODE VARCHAR(255) NULL,
       EPA_REGION VARCHAR(255) NULL,
       FACILITY_ACTIVITY_CODE VARCHAR(255) NULL,
       FACILITY_DEACTIVATION_DATE VARCHAR(255) NULL,
       FACILITY_ID VARCHAR(255) NULL,
       FACILITY_NAME VARCHAR(255) NULL,
       FACILITY_TYPE_CODE VARCHAR(255) NULL,
       FILTRATION_STATUS_CODE VARCHAR(255) NULL,
       IS_SOURCE_IND VARCHAR(255) NULL,
       IS_SOURCE_TREATED_IND VARCHAR(255) NULL,
       PRIMACY_AGENCY_CODE VARCHAR(255) NULL,
       PWSID VARCHAR(255) NULL,
       PWS_ACTIVITY_CODE VARCHAR(255) NULL,
       PWS_DEACTIVATION_DATE VARCHAR(255) NULL,
       PWS_TYPE_CODE VARCHAR(255) NULL,
       SELLER_PWSID VARCHAR(255) NULL,
       SELLER_PWS_NAME VARCHAR(255) NULL,
       SELLER_TREATMENT_CODE VARCHAR(255) NULL,
       STATE_FACILITY_ID VARCHAR(255) NULL,
       SUBMISSION_STATUS_CODE VARCHAR(255) NULL,
       WATER_TYPE_CODE VARCHAR(255) NULL
);


load data local infile '/tmp/ENFORCEMENT_ACTION.csv' into table ENFORCEMENT_ACTION fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/GEOGRAPHIC_AREA.csv' into table GEOGRAPHIC_AREA fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/LCR_SAMPLE.csv' into table LCR_SAMPLE fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/LCR_SAMPLE_RESULT.csv' into table LCR_SAMPLE_RESULT fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/SERVICE_AREA.csv' into table SERVICE_AREA fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/TREATMENT.csv' into table TREATMENT fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/VIOLATION.csv' into table VIOLATION fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/VIOLATION_ENF_ASSOC.csv' into table VIOLATION_ENF_ASSOC fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/WATER_SYSTEM.csv' into table WATER_SYSTEM fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;

load data local infile '/tmp/WATER_SYSTEM_FACILITY.csv' into table WATER_SYSTEM_FACILITY fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows;
